---
version: 0.0.1
name: minecraft.seattleacademy.org
description: Transform your plain text into static websites and blogs
url: https://minecraft.seattleacademy.org
repository: https://github.com/seattleacademy/minecraft.seattleacademy.org
timezone: America/Los_Angeles
exclude:
- ".gitignore"
- CNAME
- logs
- schematics
- readme.md